### ISSUE TITLE
Default case in dispatchTouchEvent method

### ISSUE THREAD

**Issue by Martinsandoval** [HOLDfoot/dispatchTouchEvent#1]
Hi! 
In dispatchTouchEvent/app/src/main/java/com/example/lenovo/viewdispatchdemo/CustomButtom.java
 it's convenient to add a case by default, when the event dispatch is different. 

Example:

```
case default:
                Log.e("ButtonTouch","other dispatch touched");
                break;
```

**Comment by HOLDfoot** [comment]
Hi,
Thanks,
I just add the default case.
